name: 'syndicate_address_transform'
version: '1.0.0'

config-version: 2

profile: 'syndicate_address_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  bq_dataset: "{{ env_var('BQ_DATASET') }}"
